# Generated by Django 5.2.10 on 2026-01-24 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('stock_type', models.CharField(choices=[('MAG7', 'Magnificent 7'), ('INDEX', 'Market Index')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='ATRAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('current_atr', models.DecimalField(decimal_places=4, help_text='Current 14-day ATR', max_digits=12)),
                ('current_daily_range', models.DecimalField(decimal_places=4, help_text="Today's high-low range", max_digits=12)),
                ('consecutive_tight_days', models.IntegerField(default=0, help_text='Days with daily range at or below ATR')),
                ('avg_volume_20d', models.BigIntegerField(blank=True, help_text='20-day average volume', null=True)),
                ('current_volume', models.BigIntegerField(blank=True, null=True)),
                ('volume_ratio', models.DecimalField(blank=True, decimal_places=4, help_text='Current volume / 20-day average', max_digits=8, null=True)),
                ('is_consolidating', models.BooleanField(default=False, help_text='True if 3+ consecutive tight days')),
                ('volume_spike_detected', models.BooleanField(default=False, help_text='True if volume > 1.5x average during consolidation')),
                ('breakout_probability', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='LOW', max_length=10)),
                ('price_at_analysis', models.DecimalField(decimal_places=4, help_text='Closing price when analysis was run', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atr_analyses', to='stocks.stock')),
            ],
            options={
                'verbose_name_plural': 'ATR Analyses',
                'ordering': ['-date'],
                'unique_together': {('stock', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PriceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('open', models.DecimalField(decimal_places=4, max_digits=12)),
                ('high', models.DecimalField(decimal_places=4, max_digits=12)),
                ('low', models.DecimalField(decimal_places=4, max_digits=12)),
                ('close', models.DecimalField(decimal_places=4, max_digits=12)),
                ('volume', models.BigIntegerField()),
                ('true_range', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('atr_14', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('daily_range', models.DecimalField(blank=True, decimal_places=4, help_text='High - Low for the day', max_digits=12, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_data', to='stocks.stock')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['stock', 'date'], name='stocks_pric_stock_i_877682_idx')],
                'unique_together': {('stock', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('CONSOLIDATION_START', 'Consolidation Started'), ('VOLUME_SPIKE', 'Volume Spike Detected'), ('BREAKOUT_READY', 'Breakout Ready'), ('BREAKOUT_OCCURRED', 'Breakout Occurred')], max_length=20)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='stocks.atranalysis')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='stocks.stock')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_read', 'created_at'], name='stocks_aler_is_read_25fd99_idx'), models.Index(fields=['email_sent'], name='stocks_aler_email_s_8d5e35_idx')],
            },
        ),
    ]
