# Generated by Django 5.2.10 on 2026-01-24 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atranalysis',
            name='confidence_score',
            field=models.IntegerField(default=0, help_text='0-100 composite score: tightness + volume + days'),
        ),
        migrations.AddField(
            model_name='atranalysis',
            name='range_tightness_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='How much below ATR the daily range is (%)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='earnings_time',
            field=models.CharField(blank=True, choices=[('BMO', 'Before Market Open'), ('AMC', 'After Market Close'), ('TBD', 'TBD')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='next_earnings_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
