# Generated by Django 5.2.10 on 2026-01-24 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stocks', '0002_atranalysis_confidence_score_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=50)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=10)),
                ('email_alerts', models.BooleanField(default=True)),
                ('alert_on_consolidation', models.BooleanField(default=True)),
                ('alert_on_volume_spike', models.BooleanField(default=True)),
                ('alert_on_breakout', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserWatchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(choices=[('WATCHING', 'Watching'), ('SETTING_UP', 'Setting Up'), ('BREAKING_OUT', 'Breaking Out'), ('POSITION', 'Have Position'), ('AVOID', 'Avoid')], default='WATCHING', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('custom_tight_days_threshold', models.IntegerField(blank=True, null=True)),
                ('custom_volume_spike_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_entries', to='stocks.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['tag', 'stock__symbol'],
                'unique_together': {('user', 'stock')},
            },
        ),
    ]
